// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Paqueteria.Infrastructure.Data;

#nullable disable

namespace Paqueteria.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223023422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Paqueteria.Core.Entities.Articulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.HasKey("Id");

                    b.ToTable("articulos");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.ArticuloGuia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("GuiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("guia_id");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("peso");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("GuiaId");

                    b.ToTable("articulos_guia");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Asignacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Camion")
                        .HasColumnType("integer")
                        .HasColumnName("camion");

                    b.Property<Guid>("ChoferId")
                        .HasColumnType("uuid")
                        .HasColumnName("chofer_id");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<Guid>("IdChofer")
                        .HasColumnType("uuid");

                    b.Property<string>("NumContenedor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("num_contenedor");

                    b.Property<string>("NumContenedor2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("num_contenedor2");

                    b.Property<string>("St1")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st1");

                    b.Property<string>("St2")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st2");

                    b.Property<string>("St3")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st3");

                    b.Property<string>("St4")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st4");

                    b.HasKey("Id");

                    b.HasIndex("IdChofer");

                    b.ToTable("asignaciones");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.AsignacionGuia", b =>
                {
                    b.Property<Guid>("IdAsignacionGuia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AsignacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("asignacion_id");

                    b.Property<Guid>("GuiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("guia_id");

                    b.HasKey("IdAsignacionGuia");

                    b.HasIndex("AsignacionId");

                    b.HasIndex("GuiaId");

                    b.ToTable("asignaciones_guias");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.BitacoraAcceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClienteIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cliente_ip");

                    b.Property<bool>("Exito")
                        .HasColumnType("boolean")
                        .HasColumnName("exito");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid>("UsiarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("bitacora_accesos");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.BitacoraSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Accion")
                        .HasColumnType("integer")
                        .HasColumnName("accion");

                    b.Property<string>("ClienteIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cliente_ip");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid>("RegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("registro_id");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tabla");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("jsonb")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("jsonb")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("bitacora_sistema");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Chofer", b =>
                {
                    b.Property<Guid>("ChoferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chofer_id");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("Calle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("calle");

                    b.Property<string>("Colonia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("colonia");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<Guid>("IdMunicipio")
                        .HasColumnType("uuid")
                        .HasColumnName("id_municipio");

                    b.Property<string>("Localidad")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("localidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("NumCamion")
                        .HasColumnType("integer")
                        .HasColumnName("num_camion");

                    b.Property<int>("NumContenedor")
                        .HasColumnType("integer")
                        .HasColumnName("num_contenedor");

                    b.Property<int>("NumContenedor2")
                        .HasColumnType("integer")
                        .HasColumnName("num_contenedor2");

                    b.Property<string>("NumeroExterior")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_exterior");

                    b.Property<string>("NumeroInterior")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_interior");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("ChoferId");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("choferes");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contacto");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("DireccionComplemento")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion_complemento");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<Guid?>("MunicipioId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumConvenio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("num_convenio");

                    b.Property<string>("PolizaSeguro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("poliza_seguro");

                    b.Property<string>("Rfc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rfc");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono_2");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("SucursalId");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.DireccionGuiaSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("calle");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("colonia");

                    b.Property<Guid>("IdMunicipio")
                        .HasColumnType("uuid");

                    b.Property<string>("Localidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("localidad");

                    b.Property<Guid>("MunicipioId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipio_id");

                    b.Property<string>("NumeroExterior")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_exterior");

                    b.Property<string>("NumeroInterior")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_interior");

                    b.HasKey("Id");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("direcciones_guia_snapshot");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("calle");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("codigo_postal");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<Guid>("MunicipioId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreCorto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_corto");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rfc");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Estado", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("id");

                    b.Property<string>("Acronimo2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("acronimo_2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("estados");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Guia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<Guid>("ClienteDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_destino_id");

                    b.Property<Guid>("ClienteOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_origen_id");

                    b.Property<decimal>("CobroSeguro")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("cobro_seguro");

                    b.Property<decimal>("CostoFlete")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("costo_flete");

                    b.Property<Guid>("DireccionDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("direccion_destino_id");

                    b.Property<Guid>("DireccionOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("direccion_origen_id");

                    b.Property<DateTime>("FechaCaptura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_captura");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forma_pago");

                    b.Property<string>("ImporteTexto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("importe_texto");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("iva");

                    b.Property<decimal>("IvaRetenido")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("ivar");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("PolizaSeguro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("poliza_seguro");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("SucursalDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_destino_id");

                    b.Property<Guid>("SucursalOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_origen_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total");

                    b.Property<Guid>("UsuarioAltaId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_alta_id");

                    b.Property<Guid?>("UsuarioCobroId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_cobro_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteDestinoId");

                    b.HasIndex("ClienteOrigenId");

                    b.HasIndex("DireccionDestinoId");

                    b.HasIndex("DireccionOrigenId");

                    b.HasIndex("SucursalDestinoId");

                    b.HasIndex("SucursalOrigenId");

                    b.HasIndex("UsuarioAltaId");

                    b.HasIndex("UsuarioCobroId");

                    b.ToTable("guias");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Municipio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("municipios");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Ruta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("NumCamion")
                        .HasColumnType("integer")
                        .HasColumnName("num_camion");

                    b.Property<int?>("NumContenedor")
                        .HasColumnType("integer")
                        .HasColumnName("num_contenedor");

                    b.Property<int?>("NumContenedor2")
                        .HasColumnType("integer")
                        .HasColumnName("num_contenedor_2");

                    b.Property<Guid>("SucursalDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_destino_id");

                    b.Property<Guid>("SucursalOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_origen_id");

                    b.HasKey("Id");

                    b.HasIndex("SucursalDestinoId");

                    b.HasIndex("SucursalOrigenId");

                    b.ToTable("rutas");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Seguro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("seguros");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("calle");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("colonia");

                    b.Property<bool>("EsMatriz")
                        .HasColumnType("boolean")
                        .HasColumnName("es_matriz");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<string>("Localidad")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("localidad");

                    b.Property<Guid>("MunicipioId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroExterior")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_exterior");

                    b.Property<string>("NumeroInterior")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_interior");

                    b.Property<string>("ServidorIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("servidor_ip");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("sucursales");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultimo_acceso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.ArticuloGuia", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Guia", "Guia")
                        .WithMany("Articulos")
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Guia");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Asignacion", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Chofer", "Chofer")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdChofer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chofer");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.AsignacionGuia", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Asignacion", "Asignacion")
                        .WithMany("DetallesGuias")
                        .HasForeignKey("AsignacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Guia", "Guia")
                        .WithMany("Asignaciones")
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("Guia");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.BitacoraAcceso", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.BitacoraSistema", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Chofer", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Cliente", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Municipio");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.DireccionGuiaSnapshot", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Empresa", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Guia", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Cliente", "ClienteDestino")
                        .WithMany("GuiasRecibidas")
                        .HasForeignKey("ClienteDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Cliente", "ClienteOrigen")
                        .WithMany("GuiasEnviadas")
                        .HasForeignKey("ClienteOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.DireccionGuiaSnapshot", "DireccionDestino")
                        .WithMany()
                        .HasForeignKey("DireccionDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.DireccionGuiaSnapshot", "DireccionOrigen")
                        .WithMany()
                        .HasForeignKey("DireccionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "SucursalDestino")
                        .WithMany()
                        .HasForeignKey("SucursalDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "SucursalOrigen")
                        .WithMany()
                        .HasForeignKey("SucursalOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Usuario", "UsuarioAlta")
                        .WithMany()
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Usuario", "UsuarioCobro")
                        .WithMany()
                        .HasForeignKey("UsuarioCobroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClienteDestino");

                    b.Navigation("ClienteOrigen");

                    b.Navigation("DireccionDestino");

                    b.Navigation("DireccionOrigen");

                    b.Navigation("SucursalDestino");

                    b.Navigation("SucursalOrigen");

                    b.Navigation("UsuarioAlta");

                    b.Navigation("UsuarioCobro");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Municipio", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Ruta", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "SucursalDestino")
                        .WithMany()
                        .HasForeignKey("SucursalDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "SucursalOrigen")
                        .WithMany()
                        .HasForeignKey("SucursalOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SucursalDestino");

                    b.Navigation("SucursalOrigen");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sucursal", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Municipio", "Municipio")
                        .WithMany("Sucursales")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Asignacion", b =>
                {
                    b.Navigation("DetallesGuias");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Chofer", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Cliente", b =>
                {
                    b.Navigation("GuiasEnviadas");

                    b.Navigation("GuiasRecibidas");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Guia", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Municipio", b =>
                {
                    b.Navigation("Sucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
