// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Paqueteria.Infrastructure.Data;

#nullable disable

namespace Paqueteria.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Paqueteria.Core.Entities.Articulo", b =>
                {
                    b.Property<Guid>("IdArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_articulo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.HasKey("IdArticulo");

                    b.ToTable("articulos");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.ArticuloGuia", b =>
                {
                    b.Property<Guid>("IdArticuloGuia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_articulos_guia");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("IdArticulo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_articulo");

                    b.Property<Guid>("IdGuia")
                        .HasColumnType("uuid")
                        .HasColumnName("id_guia");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("peso");

                    b.HasKey("IdArticuloGuia");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdGuia");

                    b.ToTable("articulos_guia");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Asignacion", b =>
                {
                    b.Property<Guid>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_asignacion");

                    b.Property<int>("Camion")
                        .HasColumnType("integer")
                        .HasColumnName("camion");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<Guid>("IdChofer")
                        .HasColumnType("uuid")
                        .HasColumnName("id_chofer");

                    b.Property<string>("NumContenedor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("num_contenedor");

                    b.Property<string>("NumContenedor2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("num_contenedor2");

                    b.Property<string>("St1")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st1");

                    b.Property<string>("St2")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st2");

                    b.Property<string>("St3")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st3");

                    b.Property<string>("St4")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st4");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdChofer");

                    b.ToTable("asignaciones");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.AsignacionGuia", b =>
                {
                    b.Property<Guid>("IdAsignacionGuia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_asignacion_guia");

                    b.Property<Guid>("IdAsignacion")
                        .HasColumnType("uuid")
                        .HasColumnName("id_asignacion");

                    b.Property<Guid>("IdGuia")
                        .HasColumnType("uuid")
                        .HasColumnName("id_guia");

                    b.HasKey("IdAsignacionGuia");

                    b.HasIndex("IdAsignacion");

                    b.HasIndex("IdGuia");

                    b.ToTable("asignaciones_guias");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.BitacoraAcceso", b =>
                {
                    b.Property<Guid>("IdAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_acceso");

                    b.Property<bool>("Exito")
                        .HasColumnType("boolean")
                        .HasColumnName("exito");

                    b.Property<DateTime>("FechaAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_acceso");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IpCliente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_cliente");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_agent");

                    b.HasKey("IdAcceso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("bitacora_accesos");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.BitacoraSistema", b =>
                {
                    b.Property<Guid>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_bitacora");

                    b.Property<int>("Accion")
                        .HasColumnType("integer")
                        .HasColumnName("accion");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evento");

                    b.Property<Guid>("IdRegistroAfectado")
                        .HasColumnType("uuid")
                        .HasColumnName("id_registro_afectado");

                    b.Property<Guid>("IdSucursal")
                        .HasColumnType("uuid")
                        .HasColumnName("id_sucursal");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IpCliente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_cliente");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tabla_afectada");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_agent");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_anteriores");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_nuevos");

                    b.HasKey("IdBitacora");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdUsuario");

                    b.ToTable("bitacora_sistema");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Chofer", b =>
                {
                    b.Property<Guid>("IdChofer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_chofere");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estatus_generico");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("NumCamion")
                        .HasColumnType("integer")
                        .HasColumnName("num_camion");

                    b.Property<int>("NumContenedor")
                        .HasColumnType("integer")
                        .HasColumnName("num_contenedor");

                    b.Property<int>("NumContenedor2")
                        .HasColumnType("integer")
                        .HasColumnName("num_contenedor2");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdChofer");

                    b.ToTable("choferes");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Cliente", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contacto");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("DireccionComplemento")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion_complemento");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<Guid?>("IdMunicipio")
                        .HasColumnType("uuid")
                        .HasColumnName("id_municipio");

                    b.Property<Guid?>("IdSucursal")
                        .HasColumnType("uuid")
                        .HasColumnName("id_sucursal");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumConvenio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("num_convenio");

                    b.Property<string>("PolizaSeguro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("poliza_seguro");

                    b.Property<string>("Rfc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rfc");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono_2");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdMunicipio");

                    b.HasIndex("IdSucursal");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.DireccionGuiaSnapshot", b =>
                {
                    b.Property<Guid>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_direccion");

                    b.Property<string>("Calle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("calle");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Colonia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("colonia");

                    b.Property<Guid?>("IdMunicipio")
                        .HasColumnType("uuid")
                        .HasColumnName("id_municipio");

                    b.Property<string>("Localidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("localidad");

                    b.Property<string>("NumeroExterior")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_exterior");

                    b.Property<string>("NumeroInterior")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_interior");

                    b.HasKey("IdDireccion");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("direcciones_guia_snapshot");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Empresa", b =>
                {
                    b.Property<Guid>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Calle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("calle");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("codigo_postal");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<Guid?>("IdMunicipio")
                        .HasColumnType("uuid")
                        .HasColumnName("id_municipio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreCorto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_corto");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rfc");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Estado", b =>
                {
                    b.Property<string>("IdEstado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("id_estado");

                    b.Property<string>("Acronimo3")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("acronimo_3");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstado");

                    b.ToTable("estados");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Guia", b =>
                {
                    b.Property<Guid>("IdGuia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_guia");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<decimal>("CobroSeguro")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("cobro_seguro");

                    b.Property<decimal>("CostoFlete")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("costo_flete");

                    b.Property<DateTime>("FechaCaptura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_captura");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forma_pago");

                    b.Property<Guid>("IdClienteDestino")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_destino");

                    b.Property<Guid>("IdClienteOrigen")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_origen");

                    b.Property<Guid>("IdDireccionDestino")
                        .HasColumnType("uuid")
                        .HasColumnName("direccion_destino");

                    b.Property<Guid>("IdDireccionOrigen")
                        .HasColumnType("uuid")
                        .HasColumnName("direccion_origen");

                    b.Property<Guid>("IdSucursalDestino")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_destino");

                    b.Property<Guid>("IdSucursalOrigen")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_origen");

                    b.Property<Guid?>("IdUsuarioAlta")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_alta");

                    b.Property<Guid?>("IdUsuarioCobro")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_cobro");

                    b.Property<string>("ImporteTexto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("importe_texto");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("iva");

                    b.Property<decimal>("IvaRetenido")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("ivar");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("PolizaSeguro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("poliza_seguro");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total");

                    b.HasKey("IdGuia");

                    b.HasIndex("IdClienteDestino");

                    b.HasIndex("IdClienteOrigen");

                    b.HasIndex("IdDireccionDestino");

                    b.HasIndex("IdDireccionOrigen");

                    b.HasIndex("IdSucursalDestino");

                    b.HasIndex("IdSucursalOrigen");

                    b.HasIndex("IdUsuarioAlta");

                    b.HasIndex("IdUsuarioCobro");

                    b.ToTable("guias");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Municipio", b =>
                {
                    b.Property<Guid>("IdMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_municipio");

                    b.Property<string>("IdEstado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMunicipio");

                    b.HasIndex("IdEstado");

                    b.ToTable("municipios");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Ruta", b =>
                {
                    b.Property<Guid>("IdRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_ruta");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("IdSucursalDestino")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_destino");

                    b.Property<Guid>("IdSucursalOrigen")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_origen");

                    b.Property<int?>("NumCamion")
                        .HasColumnType("integer")
                        .HasColumnName("num_camion");

                    b.Property<int?>("NumContenedor")
                        .HasColumnType("integer")
                        .HasColumnName("num_contenedor");

                    b.Property<int?>("NumContenedor2")
                        .HasColumnType("integer")
                        .HasColumnName("num_contenedor_2");

                    b.HasKey("IdRuta");

                    b.HasIndex("IdSucursalDestino");

                    b.HasIndex("IdSucursalOrigen");

                    b.ToTable("rutas");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Seguro", b =>
                {
                    b.Property<Guid>("IdSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_seguro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdSeguro");

                    b.ToTable("seguros");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sucursal", b =>
                {
                    b.Property<Guid>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_sucursal");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("calle");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("colonia");

                    b.Property<bool>("EsMatriz")
                        .HasColumnType("boolean")
                        .HasColumnName("es_matriz");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<Guid?>("IdMunicipio")
                        .HasColumnType("uuid")
                        .HasColumnName("id_municipio");

                    b.Property<string>("IpServidorLocal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_servidor_local");

                    b.Property<string>("Localidad")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("localidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroExterior")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_exterior");

                    b.Property<string>("NumeroInterior")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_interior");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdSucursal");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("sucursales");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultimo_acceso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usarname");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.ArticuloGuia", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Guia", "Guia")
                        .WithMany("Articulos")
                        .HasForeignKey("IdGuia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Guia");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Asignacion", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Chofer", "Chofer")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdChofer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chofer");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.AsignacionGuia", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Asignacion", "Asignacion")
                        .WithMany("DetallesGuias")
                        .HasForeignKey("IdAsignacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Guia", "Guia")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdGuia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("Guia");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.BitacoraAcceso", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Usuario", "Usuario")
                        .WithMany("Accesos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.BitacoraSistema", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Usuario", "Usuario")
                        .WithMany("BitacorasSistema")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Cliente", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Municipio");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.DireccionGuiaSnapshot", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Empresa", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Guia", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Cliente", "ClienteDestino")
                        .WithMany("GuiasRecibidas")
                        .HasForeignKey("IdClienteDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Cliente", "ClienteOrigen")
                        .WithMany("GuiasEnviadas")
                        .HasForeignKey("IdClienteOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.DireccionGuiaSnapshot", "DireccionDestino")
                        .WithMany()
                        .HasForeignKey("IdDireccionDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.DireccionGuiaSnapshot", "DireccionOrigen")
                        .WithMany()
                        .HasForeignKey("IdDireccionOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "SucursalDestino")
                        .WithMany()
                        .HasForeignKey("IdSucursalDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "SucursalOrigen")
                        .WithMany()
                        .HasForeignKey("IdSucursalOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Usuario", "UsuarioAlta")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAlta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paqueteria.Core.Entities.Usuario", "UsuarioCobro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCobro")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClienteDestino");

                    b.Navigation("ClienteOrigen");

                    b.Navigation("DireccionDestino");

                    b.Navigation("DireccionOrigen");

                    b.Navigation("SucursalDestino");

                    b.Navigation("SucursalOrigen");

                    b.Navigation("UsuarioAlta");

                    b.Navigation("UsuarioCobro");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Municipio", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Estado", "Estado")
                        .WithMany("Municipios")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Ruta", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "SucursalDestino")
                        .WithMany("RutasDestino")
                        .HasForeignKey("IdSucursalDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Sucursal", "SucursalOrigen")
                        .WithMany("RutasOrigen")
                        .HasForeignKey("IdSucursalOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SucursalDestino");

                    b.Navigation("SucursalOrigen");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sucursal", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Municipio", "Municipio")
                        .WithMany("Sucursales")
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Asignacion", b =>
                {
                    b.Navigation("DetallesGuias");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Chofer", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Cliente", b =>
                {
                    b.Navigation("GuiasEnviadas");

                    b.Navigation("GuiasRecibidas");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Estado", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Guia", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Municipio", b =>
                {
                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sucursal", b =>
                {
                    b.Navigation("RutasDestino");

                    b.Navigation("RutasOrigen");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Usuario", b =>
                {
                    b.Navigation("Accesos");

                    b.Navigation("BitacorasSistema");
                });
#pragma warning restore 612, 618
        }
    }
}
