// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Paqueteria.Infrastructure.Data;

#nullable disable

namespace Paqueteria.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Paqueteria.Core.Entities.Catalogos.Estado", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Acronimo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acronimo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pais");

                    b.HasKey("Id");

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Catalogos.Municipio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("nombre");

                    b.Property<string>("SatId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sat_id");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("municipios", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.ArticuloGuia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Alto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<int>("Cantidad")
                        .HasPrecision(10)
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("ClaveMaterialPeligrosoSat")
                        .HasColumnType("text");

                    b.Property<string>("ClaveProdServSat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaveTipoEmbalajeSat")
                        .HasColumnType("text");

                    b.Property<string>("ClaveUnidadSat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsMaterialPeligroso")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GuiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("guia_id");

                    b.Property<decimal>("Largo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PesoUnitarioKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("peso_unidad");

                    b.Property<decimal>("ValorUnidad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_unidad");

                    b.Property<Guid>("guia_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("GuiaId");

                    b.HasIndex("guia_id");

                    b.ToTable("articulos_guia", null, t =>
                        {
                            t.Property("guia_id")
                                .HasColumnName("guia_id1");
                        });
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Asignacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChoferId")
                        .HasColumnType("uuid")
                        .HasColumnName("chofer_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaPartida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_partida");

                    b.Property<string>("St1")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st1");

                    b.Property<string>("St2")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st2");

                    b.Property<string>("St3")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st3");

                    b.Property<string>("St4")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("st4");

                    b.Property<Guid>("SucursalDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_destino_id");

                    b.Property<Guid>("SucursalOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_origen_id");

                    b.HasKey("Id");

                    b.HasIndex("ChoferId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SucursalDestinoId");

                    b.HasIndex("SucursalOrigenId");

                    b.ToTable("asignaciones", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Camion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("NumCamion")
                        .HasColumnType("text")
                        .HasColumnName("num_camion");

                    b.Property<string>("Placa")
                        .HasColumnType("text")
                        .HasColumnName("placa");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("camiones", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Chofer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<Guid?>("CamionId")
                        .HasColumnType("uuid")
                        .HasColumnName("camion_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumCamion")
                        .HasColumnType("text");

                    b.Property<string>("NumContenedor")
                        .HasColumnType("text");

                    b.Property<string>("NumContenedor2")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("CamionId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("choferes", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contacto");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumConvenio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("num_convenio");

                    b.Property<string>("PolizaSeguro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("poliza_seguro");

                    b.Property<string>("Rfc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rfc");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono_2");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Rfc")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.DireccionCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("direcciones_clientes", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.DireccionGuiaSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("direcciones_guia_snapshot", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreCorto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_corto");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rfc");

                    b.HasKey("Id");

                    b.HasIndex("Rfc")
                        .IsUnique();

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.FolioSucursal", b =>
                {
                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<int>("UltimoConsecutivo")
                        .HasColumnType("integer")
                        .HasColumnName("ultimo_consecutivo");

                    b.HasKey("SucursalId");

                    b.ToTable("folios_sucursales", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Guia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AsignacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("asignacion_id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<Guid>("ClienteDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_destino_id");

                    b.Property<Guid>("ClienteOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_origen_id");

                    b.Property<decimal>("CobroSeguro")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("cobro_seguro");

                    b.Property<bool>("CondonaIva")
                        .HasColumnType("boolean")
                        .HasColumnName("condona_iva");

                    b.Property<Guid>("DireccionDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("direccion_destino_id");

                    b.Property<Guid>("DireccionOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("direccion_origen_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal>("EntregaA")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("entrega_a");

                    b.Property<bool>("EstaAsegurado")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_asegurado");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaCaptura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_captura");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal>("Flete")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("flete");

                    b.Property<int>("FormaPago")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pago");

                    b.Property<string>("ImporteTexto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("importe_texto");

                    b.Property<decimal>("Iva")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("iva");

                    b.Property<decimal>("IvaRetenido")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("ivar");

                    b.Property<decimal>("Lineas")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("lineas");

                    b.Property<decimal>("Maniobras")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("maniobras");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("Peaje")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("peaje");

                    b.Property<string>("PolizaSeguro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("poliza_seguro");

                    b.Property<decimal>("Recoleccion")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("recoleccion");

                    b.Property<Guid?>("SeguroId")
                        .HasColumnType("uuid")
                        .HasColumnName("seguro_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("SucursalDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_destino_id");

                    b.Property<Guid>("SucursalOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_origen_id");

                    b.Property<decimal>("Total")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("total");

                    b.Property<Guid>("UsuarioAltaId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_alta_id");

                    b.Property<Guid?>("UsuarioCobroId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_cobro_id");

                    b.HasKey("Id");

                    b.HasIndex("AsignacionId");

                    b.HasIndex("ClienteDestinoId");

                    b.HasIndex("ClienteOrigenId");

                    b.HasIndex("DireccionDestinoId");

                    b.HasIndex("DireccionOrigenId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SeguroId");

                    b.HasIndex("SucursalDestinoId");

                    b.HasIndex("SucursalOrigenId");

                    b.HasIndex("UsuarioAltaId");

                    b.HasIndex("UsuarioCobroId");

                    b.ToTable("guias", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.GuiaTransbordo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AsignacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaEscaneoIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEscaneoSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GuiaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SucursalTransbordoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioRegistroId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AsignacionId");

                    b.HasIndex("GuiaId");

                    b.HasIndex("SucursalTransbordoId");

                    b.HasIndex("GuiaId", "FechaEscaneoIngreso");

                    b.ToTable("guia_transbordos", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Ruta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<Guid>("SucursalDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_destino_id");

                    b.Property<Guid>("SucursalOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_origen_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SucursalDestinoId");

                    b.HasIndex("SucursalOrigenId");

                    b.ToTable("rutas", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Seguro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("seguros", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("EsMatriz")
                        .HasColumnType("boolean")
                        .HasColumnName("es_matriz");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("ServidorIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("servidor_ip");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("sucursales", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sat.Articulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClaveSat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clave");

                    b.Property<string>("MaterialPeligroso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("material_peligroso");

                    b.Property<string>("Similares")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("similares");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<DateTime>("VigenciaDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_desde");

                    b.Property<DateTime>("VigenciaHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_hasta");

                    b.HasKey("Id");

                    b.HasIndex("ClaveSat");

                    b.ToTable("articulos", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.BitacoraAcceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClienteIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cliente_ip");

                    b.Property<bool>("Exito")
                        .HasColumnType("boolean")
                        .HasColumnName("exito");

                    b.Property<DateTime>("FechaAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_acceso");

                    b.Property<Guid>("UsiarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("bitacora_accesos", "sys");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.BitacoraSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Accion")
                        .HasColumnType("integer")
                        .HasColumnName("accion");

                    b.Property<string>("ClienteIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cliente_ip");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid>("RegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("registro_id");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tabla");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("jsonb")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("jsonb")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("bitacora_sistema", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("roles_permisos", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultimo_acceso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Catalogos.Municipio", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Catalogos.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.ArticuloGuia", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Sat.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Guia", "Guia")
                        .WithMany()
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Guia", null)
                        .WithMany("ArticulosGuia")
                        .HasForeignKey("guia_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Guia");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Asignacion", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Chofer", "Chofer")
                        .WithMany()
                        .HasForeignKey("ChoferId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Sucursal", "SucursalDestino")
                        .WithMany()
                        .HasForeignKey("SucursalDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Sucursal", "SucursalOrigen")
                        .WithMany()
                        .HasForeignKey("SucursalOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chofer");

                    b.Navigation("Empresa");

                    b.Navigation("SucursalDestino");

                    b.Navigation("SucursalOrigen");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Camion", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Chofer", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Camion", "Camion")
                        .WithMany()
                        .HasForeignKey("CamionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Paqueteria.Core.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("ChoferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("calle");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("codigo_postal");

                            b1.Property<string>("Colonia")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("colonia");

                            b1.Property<string>("Localidad")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("localidad");

                            b1.Property<Guid>("MunicipioId")
                                .HasColumnType("uuid")
                                .HasColumnName("municipio_id");

                            b1.Property<string>("NumeroExterior")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("numero_exterior");

                            b1.Property<string>("NumeroInterior")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("numero_interior");

                            b1.HasKey("ChoferId");

                            b1.HasIndex("MunicipioId");

                            b1.ToTable("choferes");

                            b1.WithOwner()
                                .HasForeignKey("ChoferId");

                            b1.HasOne("Paqueteria.Core.Entities.Catalogos.Municipio", "Municipio")
                                .WithMany()
                                .HasForeignKey("MunicipioId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("Municipio");
                        });

                    b.Navigation("Camion");

                    b.Navigation("Direccion");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Cliente", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.DireccionCliente", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Cliente", "Cliente")
                        .WithMany("Direcciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Paqueteria.Core.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("DireccionClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("calle");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("codigo_postal");

                            b1.Property<string>("Colonia")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("colonia");

                            b1.Property<string>("Localidad")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("localidad");

                            b1.Property<Guid>("MunicipioId")
                                .HasColumnType("uuid")
                                .HasColumnName("municipio_id");

                            b1.Property<string>("NumeroExterior")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("numero_exterior");

                            b1.Property<string>("NumeroInterior")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("numero_interior");

                            b1.HasKey("DireccionClienteId");

                            b1.HasIndex("MunicipioId");

                            b1.ToTable("direcciones_clientes");

                            b1.WithOwner()
                                .HasForeignKey("DireccionClienteId");

                            b1.HasOne("Paqueteria.Core.Entities.Catalogos.Municipio", "Municipio")
                                .WithMany()
                                .HasForeignKey("MunicipioId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("Municipio");
                        });

                    b.Navigation("Cliente");

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.DireccionGuiaSnapshot", b =>
                {
                    b.OwnsOne("Paqueteria.Core.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("DireccionGuiaSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("calle");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("codigo_postal");

                            b1.Property<string>("Colonia")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("colonia");

                            b1.Property<string>("Localidad")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("localidad");

                            b1.Property<Guid>("MunicipioId")
                                .HasColumnType("uuid")
                                .HasColumnName("municipio_id");

                            b1.Property<string>("NumeroExterior")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("numero_exterior");

                            b1.Property<string>("NumeroInterior")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("numero_interior");

                            b1.HasKey("DireccionGuiaSnapshotId");

                            b1.HasIndex("MunicipioId");

                            b1.ToTable("direcciones_guia_snapshot");

                            b1.WithOwner()
                                .HasForeignKey("DireccionGuiaSnapshotId");

                            b1.HasOne("Paqueteria.Core.Entities.Catalogos.Municipio", "Municipio")
                                .WithMany()
                                .HasForeignKey("MunicipioId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("Municipio");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Empresa", b =>
                {
                    b.OwnsOne("Paqueteria.Core.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("calle");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("codigo_postal");

                            b1.Property<string>("Colonia")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("colonia");

                            b1.Property<string>("Localidad")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("localidad");

                            b1.Property<Guid>("MunicipioId")
                                .HasColumnType("uuid")
                                .HasColumnName("municipio_id");

                            b1.Property<string>("NumeroExterior")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("numero_exterior");

                            b1.Property<string>("NumeroInterior")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("numero_interior");

                            b1.HasKey("EmpresaId");

                            b1.HasIndex("MunicipioId");

                            b1.ToTable("empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");

                            b1.HasOne("Paqueteria.Core.Entities.Catalogos.Municipio", "Municipio")
                                .WithMany()
                                .HasForeignKey("MunicipioId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("Municipio");
                        });

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.FolioSucursal", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Sucursal", "Sucursal")
                        .WithOne()
                        .HasForeignKey("Paqueteria.Core.Entities.Remisiones.FolioSucursal", "SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Guia", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Asignacion", "Asignacion")
                        .WithMany("Guias")
                        .HasForeignKey("AsignacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Cliente", "ClienteDestino")
                        .WithMany()
                        .HasForeignKey("ClienteDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Cliente", "ClienteOrigen")
                        .WithMany()
                        .HasForeignKey("ClienteOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.DireccionGuiaSnapshot", "DireccionDestino")
                        .WithMany()
                        .HasForeignKey("DireccionDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.DireccionGuiaSnapshot", "DireccionOrigen")
                        .WithMany()
                        .HasForeignKey("DireccionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Seguro", "Seguro")
                        .WithMany()
                        .HasForeignKey("SeguroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Sucursal", "SucursalDestino")
                        .WithMany()
                        .HasForeignKey("SucursalDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Sucursal", "SucursalOrigen")
                        .WithMany()
                        .HasForeignKey("SucursalOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Sistema.Usuario", "UsuarioAlta")
                        .WithMany()
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Sistema.Usuario", "UsuarioCobro")
                        .WithMany()
                        .HasForeignKey("UsuarioCobroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asignacion");

                    b.Navigation("ClienteDestino");

                    b.Navigation("ClienteOrigen");

                    b.Navigation("DireccionDestino");

                    b.Navigation("DireccionOrigen");

                    b.Navigation("Empresa");

                    b.Navigation("Seguro");

                    b.Navigation("SucursalDestino");

                    b.Navigation("SucursalOrigen");

                    b.Navigation("UsuarioAlta");

                    b.Navigation("UsuarioCobro");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.GuiaTransbordo", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Asignacion", "Asignacion")
                        .WithMany()
                        .HasForeignKey("AsignacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Guia", "Guia")
                        .WithMany()
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Sucursal", "SucursalTransbordo")
                        .WithMany()
                        .HasForeignKey("SucursalTransbordoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("Guia");

                    b.Navigation("SucursalTransbordo");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Ruta", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Sucursal", "SucursalDestino")
                        .WithMany()
                        .HasForeignKey("SucursalDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Sucursal", "SucursalOrigen")
                        .WithMany()
                        .HasForeignKey("SucursalOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("SucursalDestino");

                    b.Navigation("SucursalOrigen");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Seguro", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Sucursal", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Paqueteria.Core.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("SucursalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("calle");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("codigo_postal");

                            b1.Property<string>("Colonia")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("colonia");

                            b1.Property<string>("Localidad")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("localidad");

                            b1.Property<Guid>("MunicipioId")
                                .HasColumnType("uuid")
                                .HasColumnName("municipio_id");

                            b1.Property<string>("NumeroExterior")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("numero_exterior");

                            b1.Property<string>("NumeroInterior")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("numero_interior");

                            b1.HasKey("SucursalId");

                            b1.HasIndex("MunicipioId");

                            b1.ToTable("sucursales");

                            b1.HasOne("Paqueteria.Core.Entities.Catalogos.Municipio", "Municipio")
                                .WithMany()
                                .HasForeignKey("MunicipioId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("SucursalId");

                            b1.Navigation("Municipio");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.BitacoraAcceso", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Sistema.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.BitacoraSistema", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Sistema.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.Permiso", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.Rol", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.RolPermiso", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Sistema.Permiso", "Permiso")
                        .WithMany("RolPermiso")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Sistema.Rol", "Rol")
                        .WithMany("RolPermiso")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.Usuario", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Remisiones.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.UsuarioRol", b =>
                {
                    b.HasOne("Paqueteria.Core.Entities.Sistema.Rol", "Rol")
                        .WithMany("UsuarioRol")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paqueteria.Core.Entities.Sistema.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Asignacion", b =>
                {
                    b.Navigation("Guias");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Cliente", b =>
                {
                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Remisiones.Guia", b =>
                {
                    b.Navigation("ArticulosGuia");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.Permiso", b =>
                {
                    b.Navigation("RolPermiso");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.Rol", b =>
                {
                    b.Navigation("RolPermiso");

                    b.Navigation("UsuarioRol");
                });

            modelBuilder.Entity("Paqueteria.Core.Entities.Sistema.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
