<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>c0d2c6e2-f8c4-455f-9dd8-f6c5d143dc09</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.3" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.3" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.2" />
      <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Paqueteria.Application\Paqueteria.Application.csproj" />
      <ProjectReference Include="..\Paqueteria.Core\Paqueteria.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Data\Migrations\" />
    </ItemGroup>

</Project>
